#!/usr/bin/env bash

# This is a bash utility to help with fresh install of Ubuntu
# Module: ADD PPA
# Version:2.1
# Author: Prasad Tengse
# Licence: GPLv3
# Github Repository: https://github.com/tprasadtp/ubuntu-after-effects
# Requirements - Bash v4.4 and above
#              - Have common sense.
#
# ------------------------------------------------------------------------------

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Changelogs~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# v1.0      - Initial decouple from monilithic script
# v2.0      - Rewrite modular
# v2.1      - Rewrite to pass shellcheck better organization

# ------------------------------------------------------------------------------

#Adding PPAs function
add_ppa_legacy ()
{
  # This function adds PPAs listed below. This function is obsolete and is not used any more!
  # Do not use this on any install other than Ubuntu with Unity
  #Adding Latest Graphic drivers to support
  #Remove # below if needed system might be unstable ??
  #sudo add-apt-repository -y ppa:oibaf/graphics-drivers
  echo -n "\nAdding PPAs"
  #Webupd8 PPA
  LOG_AND_PRINT "\nAdding Webupd8 PPA"
  sudo add-apt-repository -y ppa:nilarimogard/webupd8 >>"$SCRIPT_LOG"
  #NEMO
  LOG_AND_PRINT "\nAdding Nemo PPA"
  sudo add-apt-repository -y ppa:webupd8team/nemo >>"$SCRIPT_LOG"
  #PPA MANAGER
  LOG_AND_PRINT "\nAdding PPA manager "
  sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager >>"$SCRIPT_LOG"
  #Libre Office
  LOG_AND_PRINT "\nAdding Libre Office PPA"
  sudo add-apt-repository -y ppa:libreoffice/ppa >>"$SCRIPT_LOG"
  #Ubuntu Make
  LOG_AND_PRINT "\nAdding ubuntu make PPA"
  sudo add-apt-repository -y ppa:ubuntu-desktop/ubuntu-make >>"$SCRIPT_LOG"
  #Macubuntu Noobslab & Apps
  LOG_AND_PRINT "\nAdding Noobslab PPA"
  sudo add-apt-repository -y ppa:noobslab/macbuntu >>"$SCRIPT_LOG"
  #Noobslabs Themes
  sudo add-apt-repository -y ppa:noobslab/themes >>"$SCRIPT_LOG"
  #Handbrake
  LOG_AND_PRINT "\nAdding Handbrake PPA"
  sudo add-apt-repository -y ppa:stebbins/handbrake-releases >>"$SCRIPT_LOG"
  #Recent Notification Indicator
  LOG_AND_PRINT "\nAdding recent-notifications PPA"
  sudo add-apt-repository -y ppa:jconti/recent-notifications >>$SCRIPT_LOG"

  #Indicators in Status Bar
  LOG_AND_PRINT "\nAdding Altero PPA"
  sudo add-apt-repository -y ppa:atareao/atareao >>$SCRIPT_LOG"
  #Firefox Aurora
  LOG_AND_PRINT "\nAdding Firefox PPA"
  sudo add-apt-repository -y ppa:ubuntu-mozilla-daily/firefox-aurora >>"$SCRIPT_LOG"
  #GIMP
  LOG_AND_PRINT "\nAdding GIMP PPA"
  sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp >>"$SCRIPT_LOG"
  printf "\nDone adding PPAs"
  ##After adding repos &PPAs update apt cache
  printf "\nUpdating cache"
  sudo apt update && sudo -y apt dist-upgrade &>>"$SCRIPT_LOG"

}

add_ppa_modular ()
{
  # Function Reads the file ./data/lists/PPA.list and adds the ppa one by one
  while IFS= read line
    do
         LOG_AND_PRINT "\nAdding PPA :$line:\n"
         DEBUG "$line"
         sudo add-apt-repository -y $line >>"$SCRIPT_LOG"
    done < "$PPA_LIST"
    printf "\n${COLOR_BLUE}:Done adding PPA_LIST.${RESET_COLOR}"
}

add_ppa_modular_extra ()
{
  # Function Reads the file ./data/lists/PPA_EXTRA.list and adds the ppa one by one
  while IFS= read line
    do
         LOG_AND_PRINT "\nAdding from EXTRA PPA List :${line}:\n"
         DEBUG "\nAdding PPA :$line"
         if sudo add-apt-repository -y "$line" >> "$SCRIPT_LOG" ; then
	           LOG_AND_PRINT "\nDone!"
          else
	            LOG_AND_PRINT "\nSome error occured during adding  ${line} PPA, Ignoring and moving on!"
          fi
    done < "$PPA_LIST_EXTRA"
    printf "\n${COLOR_BLUE}:Done adding PPA_LIST_EXTRA.${RESET_COLOR}"
}
