#!/bin/bash

KERNEL_SERIES=$(uname -r |cut -d. -f1-2)
#AMD PREBUILT DEB download
DRIVER1=https://www2.ati.com/drivers/linux/fglrx_15.302-0ubuntu1_amd64_ub_14.01.deb
DRIVER2=https://www2.ati.com/drivers/linux/fglrx-core_15.302-0ubuntu1_amd64_ub_14.01.deb
DRIVER3=https://www2.ati.com/drivers/linux/fglrx-dev_15.302-0ubuntu1_amd64_ub_14.01.deb
DRIVER4=https://www2.ati.com/drivers/linux/fglrx-amdcccle_15.302-0ubuntu1_amd64_ub_14.01.deb
install_catalyst ()
{
  DEBUG "Entered Catalyst Install Functions"
     LOG_AND_PRINT "Attempting to install Catalyst Drivers"
     mkdir fglrx && cd fglrx
     LOG_AND_PRINT "Getting File: fglrx..."
     wget $DRIVER1 >>$SCRIPT_LOG && echo -n "fglrx:Done"
     LOG_AND_PRINT "Getting File: fglrx-core..."
     wget $DRIVER2 >>$SCRIPT_LOG && echo -n "fglrx-core:Done"
     LOG_AND_PRINT "Getting File: fglrx-dev..."
     wget $DRIVER2 >>$SCRIPT_LOG && echo -n "fglrx-dev:Done"
     LOG_AND_PRINT "Getting File: fglrx-amdccle..."
     wget $DRIVER2 >>$SCRIPT_LOG && echo -n "fglrx-amdccle:Done"
     LOG_AND_PRINT "Copying and backing up X.org config file"
     sudo cp /etc/X11/xorg.conf /etc/X11/xorg.conf.BAK && LOG_AND_PRINT "Done"
     LOG_AND_PRINT "Installing Essentials for Catalyst..."
     sudo apt-get install -s -y linux-headers-generic build-essential cdbs fakeroot dh-make debhelper debconf libstdc++6 dkms libqtgui4 execstack libelfg0 dh-modaliases ia32-libs &>>$SCRIPT_LOG && LOG_AND_PRINT "Installing Dependencies: Done!"
     sudo dpkg -i --dry-run fglrx*.deb >>$SCRIPT_LOG || LOG_AND_PRINT "Errors Occured during Catalyst installation. please look at log file"
     LOG_AND_PRINT "Initializing Adapters: If errors occured DO NOT Reboot your PC!!"
     #sudo aticonfig --initial -f --adapter=all || LOG_AND_PRINT "Errors during Adapter Initialization. Plase do NOT!!! reboot!! "
     LOG_AND_PRINT "Installing Drivers for H/W Acceleration"
     sudo apt-get install -y -s xvba-va-driver libva-glx1 vainfo >>$SCRIPT_LOG && LOG_AND_PRINT "Done!"
     cd .. && rm -rf fglrx && LOG_AND_PRINT "Removed DIR:fglrx"
DEBUG "Exiting Catalyst Install functions "
#Ends Compatibily check
}
