#!/bin/sh
install_apps1(){
DEBUG "Entered ${FUNCNAME[0]}"
#Accept some EULA Crap
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
#Install starts here
LOG_AND_PRINT "Installing Phase 1..."
LOG_AND_PRINT "Installing Usual tools required"
sudo apt-get -y -q install apt-xapian-index unity-tweak-tool vlc gimp ubuntu-restricted-extras ubuntu-restricted-addons chromium-browser nautilus-dropbox p7zip-full nautilus-admin playonlinux arc-theme dconf-editor spotify-client caffeine pidgin pidgin-gnome-keyring flashplugin-installer bleachbit darktable compiz-plugins-extra compiz-plugins-main compiz-plugins-main-default compizconfig-settings-manager compiz-plugins docky variety icedtea-8-plugin openjdk-8-jre gdebi  imwheel plank insync laptop-mode-tools git audacity ppa-purge gufw lm-sensors handbrake-gtk handbrake-cli indicator-netspeed syspeek indicator-multiload pavucontrol gparted synaptic lib32gcc1 >>$SCRIPT_LOG && LOG_AND_PRINT "Packages of Phase 1 installed"

#Essentials
LOG_AND_PRINT "Installing Phase 2..."
LOG_AND_PRINT "Installing tools"
#added after running script so not tested
sudo apt-get install -s -y adb fastboot audacity  >>$SCRIPT_LOG && LOG_AND_PRINT "Phase 2: Packages installed"
}
