#!/bin/sh
test_conflicting_apps ()
{
  DEBUG "Entered test_conflicting_apps"
  LOG_AND_PRINT "Checking if conflicting apps are running"
  for lock in synaptic update-manager software-center apt-get dpkg aptitude
  do
    if ps -U root -u root u | grep $lock | grep -v grep > /dev/null;
       then
       {
       LOG_AND_PRINT "Installation won't work. Please close $lock first then try again.";
       exit
       }
       else
       DEBUG "$lock not running, Proceeding with installation"
     fi
   done
   DEBUG "Exiting test_conflicting_apps"
}
