#!/usr/bin/env bash
# shellcheck disable=SC2059
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 6)
#RED=$(tput setaf 1)
NC=$(tput sgr 0)
#default config-files directory
SHARED_DIR="/home/$USER/Desktop"

if command -v rsync >&/dev/null; then
  printf "${BLUE}Copying files to ${SHARED_DIR}...${NC}\n"
  rsync -Ea --recursive \
  --exclude '*.md*' \
  --exclude '*.MD*' \
  --exclude '.git' \
  --exclude 'rsync-shared' \
  --exclude '.gitignore' \
  --exclude '.travis.yml' \
  --exclude 'screenshots' \
  --exclude 'LICENSE' \
  --exclude 'dockerfiles' \
  --exclude 'tests' \
  ./ "${SHARED_DIR}" && printf "[ INFO ] Copied\n"
else
  printf "${YELLOW}Program rsync is not installed. Please install rsync.\nThis script requires rsync.\n${NC}";
  return 1;
fi
