#!/usr/bin/env bash

# This is a bash utility to test the script in docker container
# Version:1.0
# Author: Prasad Tengse
# Licence: MIT
# Github Repository: https://github.com/tprasadtp/after-effects-ubuntu

set -e
set -o pipefail
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "Building Zesty Docker Image"
docker build -t ubuntu:ae-zesty ./dockerfiles/zesty
echo "Adding Xenial and above list to app-list.list"
echo "./data/xenial-above.list" >> ./data/app-list.list
echo "Running in Docker Zesty"
docker run -t -v "$(pwd)":/shared ubuntu:ae-zesty /bin/bash -c "cd /shared; TRAVIS=true /shared/after-effects -y -s"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
