#!/usr/bin/env bash

# This is a bash utility to test the script in docker container
# Version:1.0
# Author: Prasad Tengse
# Licence: GPLv3
# Github Repository: https://github.com/tprasadtp/after-effects-ubuntu

set -eo pipefail
readonly dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
log_file="$dir"/after-effects-logs/after-effects.log
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "Building Xenial Docker Image"
docker build -t ubuntu:ae-xenial ./dockerfiles/xenial
echo "Running in Docker Xenial"
docker run -it -e TRAVIS="$TRAVIS" -v "$(pwd)":/shared ubuntu:ae-artful /shared/after-effects --simulate --yes
echo "Exit code from docker run is: $?"
echo "Print Logs is set to: $PRINT_LOGS"
if [ "$PRINT_LOGS" == "true" ]; then
  echo " "
  echo " "
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  cat "$log_file"
fi
