#!/usr/bin/env bash
# shellcheck disable=SC2059

# Version:0.1
# Author: Prasad Tengse
# Licence: GPLv3
# Github Repository: https://github.com/tprasadtp/after-effects-ubuntu
set -e pipefail
spacing_string="%-15s"

## Install Python packages
pip install --upgrade pip
pip install -r ./dockerfiles/mkdocs/requirements.txt
# Build Static
echo "Building Docs"
mkdocs build -v -s
echo "Generate JSON"
mkdir -p ./cfg/json/
yamllint ./cfg/version && yml2json ./cfg/version | python -m json.tool > ./cfg/json/version
echo "Copy API Files"
cp -R ./cfg/ ./_site/cfg/
echo "Copy Netlify Files"
cp -R ./vendor/ ./_site/vendor/
cp -R ./_redirects ./_site/_redirects
cp -R ./netlify.toml ./_site/netlify.toml
echo "Commit Info"
true > ./_site/commit.txt
printf "${spacing_string}: ${TRAVIS_COMMIT:0:7}\n" "SRC Commit ID"  | tee -a ./_site/commit.txt
printf "${spacing_string}: ${TRAVIS_COMMIT_MESSAGE}\n" "SRC Message" | tee -a ./_site/commit.txt
printf "${spacing_string}: ${TRAVIS_BRANCH}\n" "Built from" | tee -a ./_site/commit.txt
# Install htmlproofer
#echo "Installing bundler dependencies"
#bundle install
# html-proofer tests
#bundle exec htmlproofer ./_site --only-4xx --check-favicon
