#!/usr/bin/env bash

# This is a bash utility to test the shellscripts in this repo using shellcheck
# Version:0.1
# Author: Prasad Tengse
# Licence: MIT
# Github Repository: https://github.com/tprasadtp/after-effects-ubuntu

set -e
set -o pipefail

if [ "$TRAVIS" == "true" ]; then
	echo "Installing shellcheck"
	echo ""
	sudo apt-get -y install shellcheck
fi
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "Testing ShellScripts"
ERRORS=()

# find all executables and run `shellcheck`
for file in $(find . -type f -not -iwholename '*.git*' -executable | sort -u); do
	if file "${file}" ; then
		{
			# ignore unused variables in pf 2059, double  quote strings  2086 2034 unused strings
			shellcheck  "${file}" && printf " [ OK ]: sucessfully linted %s\n\n" "${file}"

		} ||
		{
			# If shell check failed
			ERRORS+=("${file}")
		}
	fi
done

if [ ${#ERRORS[@]} -eq 0 ]; then
	printf "\nNo errors, hooray!!\n"
else
	echo "These files failed shellcheck: ${ERRORS[*]}"
	exit 1
fi
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
