#!/usr/bin/env bash

# This is a bash utility to test the script in docker container
# Version:1.0
# Author: Prasad Tengse
# Licence: GPLv3
# Github Repository: https://github.com/tprasadtp/after-effects-ubuntu

set -eo pipefail
readonly dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
log_file="$dir"/after-effects-logs/after-effects.log
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "Building Bionic Docker Image"
echo "Getting Bionic Daily Image"
wget http://cdimage.ubuntu.com/ubuntu-base/daily/current/bionic-base-amd64.tar.gz -O ./dockerfiles/bionic/bionic-base-amd64.tar.gz
ls -a
docker build -t ubuntu:ae-bionic ./dockerfiles/bionic
echo "Adding Xenial and above list to app-list.list"
echo "./data/xenial-above.list" >> ./data/app-list.list
echo "Running in Docker Bionic"
docker run -t -v "$(pwd)":/shared ubuntu:ae-bionic /bin/bash -c "cd /shared; TRAVIS=true ./after-effects --yes --simulate --pre-release"
echo "Exit code from docker run is: $?"
echo "Print Logs is set to: $PRINT_LOGS"
if [ "$PRINT_LOGS" == "true" ]; then
  echo " "
  echo " "
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  cat "$log_file"
fi
