#!/usr/bin/env bash
#
#                                        _  .
# \,___, .___    ___    ____   ___    ___/ _/_
# |    \ /   \  /   `  (      /   `  /   |  |
# |    | |   ' |    |  `--.  |    | ,'   |  |
# |`---' /     `.__/| \___.' `.__/| `___,'  \__/
# \                                      `
#

# This is a bash script to build jekyll website and test it with htmlproofer
# Version:1.0
# Author: Prasad Tengse
# Licence: MIT
# Github Repository: https://github.com/tprasadtp/deepankuri
# Requirements - Bash v4.4 and above
#              - jekyll and bundler

set -e # halt script on error
## Install PIP
sudo apt-get update
pip install mkdocs mkdocs-material
# Build Static
echo "Building Docs"
mkdocs build
# Install htmlproofer
echo "Installing bundler dependencies"
bundle install
# html-proofer tests
bundle exec htmlproofer ./_site --only-4xx --check-favicon
