#!/usr/bin/env bash

# This is a bash utility to test the script in docker container
# Version:1.0
# Author: Prasad Tengse
# Licence: GPLv3
# Github Repository: https://github.com/tprasadtp/after-effects-ubuntu

set -o pipefail
function main()
{
  dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
  #shellcheck disable=SC2116
  dir=$(echo "${dir/tests/}")
  log_file="$dir"/after-effects-logs/after-effects.log
  # set eo on script.
  sed -i 's/set -o pipefail/set -eo pipefail/g' "$dir"/after-effects
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "Getting Bionic Daily Image"
  wget http://cdimage.ubuntu.com/ubuntu-base/daily/current/bionic-base-amd64.tar.gz -O ./dockerfiles/bionic/bionic-base-amd64.tar.gz
  ls -a
  echo "Building Bionic Docker Image"
  docker build -t ubuntu:ae-bionic ./dockerfiles/bionic
  echo "Adding Xenial and above list to app-list.list"
  echo "./data/xenial-above.list" >> ./data/app-list.list
  echo "Running in Docker Bionic"

  docker run -it -e TRAVIS="$TRAVIS" \
  --hostname=Docker-Bionic \
  -v "$(pwd)":/shared \
  ubuntu:ae-bionic \
  /shared/after-effects --simulate --yes --pre-release

  exit_code_from_container=$?
  echo "Exit code from docker run is: $exit_code_from_container"
  echo "Print Logs is set to: $PRINT_LOGS"
  echo "Print Pre Release Logs is set to: $PRINT_PRE_RELEASE_LOGS"
  if [ "$PRINT_LOGS" == "true" ] || [ "$PRINT_PRE_RELEASE_LOGS" == "true" ]; then
    echo " "
    echo " "
    echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
    cat "$log_file"
  fi

  return "$exit_code_from_container"

}

main "$@"
